export const ChapterC = {
  C01: {
    id: 72,
    icon: "puzzle",
    color: "blue",
    secret: "StretchTheLine",
  },
  "C01.1": {
    id: 20,
    icon: "puzzle",
    color: "blue",
    secret: "CloseItUp",
  },
  C02: {
    id: 73,
    icon: "puzzle",
    color: "blue",
    secret: "DifferentConnectors",
  },
  C03: {
    id: 74,
    icon: "puzzle",
    color: "blue",
    secret: "LongLines",
  },
  C04: {
    id: 75,
    icon: "universes",
    color: "blue",
  },
  C05: {
    id: 76,
    icon: "universes",
    color: "blue",
  },
  C06: {
    id: 77,
    icon: "universes",
    color: "blue",
  },
  C07: {
    id: 78,
    icon: "universes",
    color: "blue",
  },
  C08: {
    id: 79,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  C09: {
    id: 80,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  C10: {
    id: 81,
    icon: "fish-and-jelly",
    color: "orange",
    combat: true,
  },
  C11: {
    id: 82,
    icon: "fish-and-jelly",
    color: "orange",
    combat: true,
    secret: "MiniUnderwCave",
  },
  C12: {
    id: 83,
    icon: "race",
    color: "orange",
    combat: true,
  },
  C13: {
    id: 84,
    icon: "race",
    color: "orange",
    combat: true,
  },
  "C13.1": {
    id: 2,
    icon: "water-pump",
    color: "pink",
  },
  C14: {
    id: 85,
    icon: "blocks",
    color: "orange",
    combat: true,
    secret: "OverTheBombs",
  },
  C15: {
    id: 86,
    icon: "fish-and-jelly",
    color: "orange",
    combat: true,
  },
  C16: {
    id: 87,
    icon: "race",
    color: "orange",
    combat: true,
  },
  C17: {
    id: 88,
    icon: "combat",
    color: "orange",
    combat: true,
    secret: "DrillDownAndFlyHigh",
  },
  C18: {
    id: 89,
    icon: "combat",
    color: "orange",
    combat: true,
    secret: "PiranhaTower",
  },
  C19: {
    id: 90,
    icon: "race",
    color: "orange",
    combat: true,
    secret: "InTheShortcut",
  },
  C20: {
    id: 91,
    icon: "blank",
    color: "blue",
    secret: "BlockedByUnderwCurrents",
  },
  C21: {
    id: 92,
    icon: "boss_mama-squid",
    color: "orange",
    combat: true,
    boss: true,
  },
  C22: {
    id: 93,
    icon: "blank",
    color: "blue",
  },
};
