export const ChapterA = {
  A01: {
    id: 28,
    icon: "hall",
    color: "blue",
  },
  "A01.1": {
    id: 29,
    icon: "hall",
    color: "pink",
    secret: "SecretPassage",
  },
  A02: {
    id: 30,
    icon: "hall",
    color: "blue",
  },
  "A02.1": {
    id: 21,
    icon: "hat-selection",
    color: "pink",
  },
  A03: {
    id: 31,
    icon: "hall",
    color: "blue",
  },
  "A03.1": {
    id: 12,
    icon: "diana",
    color: "pink",
    secret: "DianasStory",
  },
  A04: {
    id: 32,
    icon: "hall",
    color: "blue",
  },
  A05: {
    id: 33,
    icon: "skill-test",
    color: "blue",
  },
  A06: {
    id: 34,
    icon: "difficulty-decision",
    color: "blue",
  },
  A07: {
    id: 35,
    icon: "stars",
    color: "blue",
  },
  A08: {
    id: 36,
    icon: "stars",
    color: "blue",
  },
  A09: {
    id: 37,
    icon: "stars",
    color: "blue",
  },
  A10: {
    id: 38,
    icon: "stars",
    color: "blue",
  },
  "A10.1": {
    id: 11,
    icon: "stars",
    color: "pink",
    secret: "LookingAtTheStars",
  },
  "A10.2": {
    id: 61,
    icon: "stars",
    color: "pink",
    secret: "ExpansionInSpace",
  },
  A11: {
    id: 39,
    icon: "stars",
    color: "blue",
  },
  A12: {
    id: 40,
    icon: "blank",
    color: "blue",
  },
  A13: {
    id: 41,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  A14: {
    id: 43,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  "A14.1": {
    id: 5,
    icon: "secret-presentation",
    color: "pink",
  },
  A15: {
    id: 44,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  A16: {
    id: 45,
    icon: "conveyor-belts",
    color: "orange",
    combat: true,
  },
  A17: {
    id: 46,
    icon: "conveyor-belts",
    color: "orange",
    combat: true,
  },
  A18: {
    id: 47,
    icon: "combat",
    color: "orange",
    combat: true,
  },
  A19: {
    id: 48,
    icon: "combat",
    color: "orange",
    combat: true,
  },
  A20: {
    id: 49,
    icon: "boss_demolition",
    color: "orange",
    combat: true,
    boss: true,
  },
  A21: {
    id: 50,
    icon: "blank",
    color: "blue",
    secret: "AHardClimb",
  },
};
