export const ChapterE = {
  E01: {
    id: 122,
    icon: "puzzle",
    color: "blue",
  },
  E02: {
    id: 123,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  E03: {
    id: 124,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  "E03.1": {
    id: 125,
    icon: "puzzle",
    color: "pink",
    exploration: true,
  },
  E04: {
    id: 126,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  E05: {
    id: 127,
    icon: "timeline",
    color: "blue",
    exploration: true,
  },
  E06: {
    id: 98,
    icon: "amelia",
    color: "blue",
    exploration: true,
  },
  "E06.1": {
    id: 3,
    icon: "puzzle",
    color: "pink",
    exploration: true,
  },
  E07: {
    id: 128,
    icon: "crazy_spikes",
    color: "orange",
    combat: true,
  },
  E08: {
    id: 129,
    icon: "crazy_spikes",
    color: "orange",
    combat: true,
  },
  E09: {
    id: 130,
    icon: "crazy_lasers",
    color: "orange",
    combat: true,
  },
  E10: {
    id: 131,
    icon: "bartender",
    color: "orange",
    combat: true,
    exploration: true,
  },
  E11: {
    id: 132,
    icon: "snowy_doom",
    color: "orange",
    combat: true,
  },
  E12: {
    id: 133,
    icon: "snowman",
    color: "orange",
    combat: true,
  },
  E13: {
    id: 134,
    icon: "crazy_spikes",
    color: "orange",
    combat: true,
  },
  E14: {
    id: 135,
    icon: "killer_fish",
    color: "orange",
    combat: true,
  },
  E15: {
    id: 136,
    icon: "shelly",
    color: "orange",
    combat: true,
  },
  "E15.1": {
    id: 137,
    icon: "crazy_tower_defense",
    color: "pink",
  },
  "E15.2": {
    id: 138,
    icon: "hall",
    color: "pink",
    exploration: true,
  },
  E16: {
    id: 16,
    icon: "stars",
    color: "blue",
  },
  E17: {
    id: 139,
    icon: "squid_boss",
    color: "orange",
    combat: true,
    boss: true,
  },
  E18: {
    id: 140,
    icon: "crazy_squid_boss",
    color: "orange",
    combat: true,
    boss: true,
  },
  E19: {
    id: 141,
    icon: "broken_squid",
    color: "blue",
    exploration: true,
  },
  "E19.1": {
    id: 10,
    icon: "squids_heart",
    color: "pink",
  },
};
