const ChapterC = {
  C01: {
    id: 72,
    icon: "puzzle",
    color: "blue",
    secret: true,
    exploration: true,
  },
  "C01.1": {
    id: 20,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  C02: {
    id: 73,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  C03: {
    id: 74,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  C04: {
    id: 75,
    icon: "universes",
    color: "blue",
  },
  C05: {
    id: 76,
    icon: "universes",
    color: "blue",
  },
  C06: {
    id: 77,
    icon: "universes",
    color: "blue",
  },
  C07: {
    id: 78,
    icon: "universes",
    color: "blue",
  },
  C08: {
    id: 79,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  C09: {
    id: 80,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  C10: {
    id: 81,
    icon: "fish_and_jellyfish",
    color: "orange",
    combat: true,
  },
  C11: {
    id: 82,
    icon: "fish_and_jellyfish",
    color: "orange",
    combat: true,
    exploration: true,
  },
  C12: {
    id: 83,
    icon: "race",
    color: "orange",
    combat: true,
  },
  C13: {
    id: 84,
    icon: "race",
    color: "orange",
    combat: true,
    secret: true,
  },
  "C13.1": {
    id: 2,
    icon: "water_pump",
    color: "pink",
  },
  C14: {
    id: 85,
    icon: "blocks",
    color: "orange",
    combat: true,
    exploration: true,
  },
  C15: {
    id: 86,
    icon: "fish_and_jellyfish",
    color: "orange",
    combat: true,
  },
  C16: {
    id: 87,
    icon: "race",
    color: "orange",
    combat: true,
  },
  C17: {
    id: 88,
    icon: "combat",
    color: "orange",
    combat: true,
    exploration: true,
  },
  C18: {
    id: 89,
    icon: "combat",
    color: "orange",
    combat: true,
    exploration: true,
  },
  C19: {
    id: 90,
    icon: "race",
    color: "orange",
    combat: true,
    exploration: true,
  },
  C20: {
    id: 91,
    icon: "blank",
    color: "blue",
    exploration: true,
  },
  C21: {
    id: 92,
    icon: "mama_squid_boss",
    color: "orange",
    combat: true,
    boss: true,
  },
  C22: {
    id: 93,
    icon: "blank",
    color: "blue",
  },
};

export default ChapterC;
