const ChapterD = {
  D01: {
    id: 94,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  D02: {
    id: 95,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  D03: {
    id: 96,
    icon: "puzzle",
    color: "blue",
    secret: true,
    exploration: true,
  },
  "D03.1": {
    id: 97,
    icon: "puzzle",
    color: "pink",
    exploration: true,
  },
  D04: {
    id: 99,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  D05: {
    id: 100,
    icon: "drone",
    color: "blue",
  },
  "D05.1": {
    id: 18,
    icon: "humans",
    color: "pink",
    exploration: true,
  },
  "D05.2": {
    id: 4,
    icon: "flying_human",
    color: "pink",
  },
  D06: {
    id: 101,
    icon: "blank",
    color: "blue",
    exploration: true,
  },
  "D06.1": {
    id: 102,
    icon: "tower_defense",
    color: "pink",
    combat: true,
  },
  "D06.2": {
    id: 103,
    icon: "tower_defense",
    color: "pink",
    combat: true,
  },
  "D06.3": {
    id: 104,
    icon: "tower_defense",
    color: "pink",
    combat: true,
  },
  "D06.4": {
    id: 105,
    icon: "tower_defense_boss",
    color: "pink",
    combat: true,
    boss: true,
  },
  "D06.5": {
    id: 106,
    icon: "hall",
    color: "pink",
    exploration: true,
  },
  D07: {
    id: 107,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  D08: {
    id: 108,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  D09: {
    id: 109,
    icon: "spikes",
    color: "orange",
    combat: true,
    exploration: true,
  },
  D10: {
    id: 110,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  "D10.1": {
    id: 111,
    icon: "hall",
    color: "pink",
    exploration: true,
  },
  D11: {
    id: 112,
    icon: "basketball",
    color: "orange",
    combat: true,
  },
  D12: {
    id: 113,
    icon: "basketball",
    color: "orange",
    combat: true,
  },
  D13: {
    id: 114,
    icon: "spikes",
    color: "orange",
    combat: true,
    exploration: true,
  },
  D14: {
    id: 115,
    icon: "bubble",
    color: "orange",
    combat: true,
  },
  D15: {
    id: 116,
    icon: "present_enemy",
    color: "orange",
    combat: true,
  },
  D16: {
    id: 117,
    icon: "firework",
    color: "orange",
    combat: true,
  },
  D17: {
    id: 118,
    icon: "firework",
    color: "orange",
    combat: true,
  },
  D18: {
    id: 119,
    icon: "basketball",
    color: "orange",
    combat: true,
  },
  D19: {
    id: 120,
    icon: "helpy_boss",
    color: "orange",
    combat: true,
    boss: true,
  },
  D20: {
    id: 121,
    icon: "blank",
    color: "blue",
  },
};

export default ChapterD;
