export default {
  B01: {
    id: 51,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  B02: {
    id: 52,
    icon: "puzzle",
    color: "blue",
    exploration: true,
  },
  B03: {
    id: 53,
    icon: "puzzle",
    color: "blue",
    secret: true,
    exploration: true,
  },
  "B03.1": {
    id: 54,
    icon: "puzzle",
    color: "pink",
    exploration: true,
  },
  B04: {
    id: 55,
    icon: "squids_brain",
    color: "blue",
    secret: true,
  },
  "B04.1": {
    id: 9,
    icon: "squids_brain",
    color: "pink",
    secret: true,
  },
  "B04.2": {
    id: 19,
    icon: "firewall",
    color: "pink",
    secret: true,
  },
  "B04.3": {
    id: 1,
    icon: "squids_heart",
    color: "pink",
    secret: true,
  },
  "B04.4": {
    id: 7,
    icon: "prediction_processing_unit",
    color: "pink",
  },
  B05: {
    id: 56,
    icon: "universe",
    color: "blue",
  },
  B06: {
    id: 57,
    icon: "universe",
    color: "blue",
  },
  B07: {
    id: 58,
    icon: "universe",
    color: "blue",
  },
  B08: {
    id: 59,
    icon: "lasers",
    color: "orange",
    combat: true,
  },
  B09: {
    id: 60,
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  B10: {
    id: 62,
    icon: "laser_show",
    color: "orange",
    combat: true,
  },
  B11: {
    id: 63,
    icon: "lasers",
    color: "orange",
    combat: true,
  },
  B12: {
    id: 64,
    icon: "blocks",
    color: "orange",
    combat: true,
  },
  B13: {
    id: 65,
    icon: "conveyor_belts",
    color: "orange",
    combat: true,
  },
  B14: {
    id: 66,
    icon: "laser_show",
    color: "orange",
    combat: true,
  },
  B15: {
    id: 67,
    icon: "combat",
    color: "orange",
    combat: true,
  },
  B16: {
    id: 68,
    icon: "combat",
    color: "orange",
    combat: true,
    exploration: true,
  },
  B17: {
    id: 69,
    icon: "combat",
    color: "orange",
    combat: true,
    exploration: true,
  },
  B18: {
    id: 70,
    icon: "mr_dance_boss",
    color: "orange",
    combat: true,
    boss: true,
    exploration: true,
  },
  B19: {
    id: 71,
    icon: "blank",
    color: "blue",
  },
};
