export default {
  A01: {
    icon: "hall",
    color: "blue",
    secret: true,
  },
  "A01.1": {
    icon: "hall",
    color: "blue",
    exploration: true,
  },
  A02: {
    icon: "hall",
    color: "blue",
    secret: true,
  },
  "A02.1": {
    icon: "hat_selection",
    color: "pink",
  },
  A03: {
    icon: "hall",
    color: "blue",
    secret: true,
    exploration: true,
  },
  "A03.1": {
    icon: "diana",
    color: "pink",
  },
  A04: {
    icon: "hall",
    color: "blue",
  },
  A05: {
    icon: "skill_test",
    color: "blue",
  },
  A06: {
    icon: "difficulty_decision",
    color: "blue",
  },
  A07: {
    icon: "stars",
    color: "blue",
  },
  A08: {
    icon: "stars",
    color: "blue",
  },
  A09: {
    icon: "stars",
    color: "blue",
  },
  A10: {
    icon: "stars",
    color: "blue",
    secret: true,
  },
  "A10.1": {
    icon: "stars",
    color: "blue",
    exploration: true,
  },
  "A10.2": {
    icon: "stars",
    color: "blue",
    exploration: true,
  },
  A11: {
    icon: "stars",
    color: "blue",
  },
  A12: {
    icon: "reward",
    color: "blue",
  },
  A13: {
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  A14: {
    icon: "spikes",
    color: "orange",
    combat: true,
    secret: true,
  },
  "A14.1": {
    icon: "secret_presentation",
    color: "pink",
  },
  A15: {
    icon: "spikes",
    color: "orange",
    combat: true,
  },
  A16: {
    icon: "conveyor_belts",
    color: "orange",
    combat: true,
  },
  A17: {
    icon: "conveyor_belts",
    color: "orange",
    combat: true,
  },
  A18: {
    icon: "action",
    color: "orange",
    combat: true,
  },
  A19: {
    icon: "action",
    color: "orange",
    combat: true,
  },
  A20: {
    icon: "demolition_boss",
    color: "orange",
    combat: true,
    boss: true,
  },
  A21: {
    icon: "reward",
    color: "blue",
    exploration: true,
  },
};

export var chapterA = [
  "A01-hall-secret-color=blue",
  "A01.1-hall-exploration_point-color=blue",
  "A02-hall-secret-color=blue",
  "A02.1-hat_selection-color=pink",
  "A03-hall-secret-exploration_point-color=blue",
  "A03.1-diana-color=pink",
  "A04-hall-color=blue",
  "A05-skill_test-color=blue",
  "A06-difficulty_decision-color=blue",
  "A07-stars-color=blue",
  "A08-stars-color=blue",
  "A09-stars-color=blue",
  "A10-stars-secret-color=blue",
  "A10.1-stars-exploration_point-color=blue",
  "A10.2-stars-exploration_point-color=blue",
  "A11-stars-color=blue",
  "A12-reward-color=blue",
  "A13-spikes-difficulty_point-color=orange",
  "A14-spikes-difficulty_point-secret-color=orange",
  "A14.1-secret_presentation-color=pink",
  "A15-spikes-difficulty_point-color=orange",
  "A16-conveyor_belts-difficulty_point-color=orange",
  "A17-conveyor_belts-difficulty_point-color=orange",
  "A18-action-difficulty_point-color=orange",
  "A19-action-difficulty_point-color=orange",
  "A20-demolition_boss-difficulty_point-color=orange",
  "A21-reward-exploration_point-color=blue",
];

export var chapterB = [
  "B01-puzzle-exploration_point-color=blue",
  "B02-puzzle-exploration_point-color=blue",
  "B03-puzzle-exploration_point-secret-color=blue",
  "B03.1-puzzle-exploration_point-color=blue",
  "B04-brain-secret-color=blue",
  "B04.1-brain-secret-color=pink",
  "B04.2-firewall-secret-color=pink",
  "B04.3-emotions_module-secret-color=pink",
  "B04.4-prediction_processing_unit-color=pink",
  "B05-universes-color=blue",
  "B06-universes-color=blue",
  "B07-universes-color=blue",
  "B08-lasers-difficulty_point-color=orange",
  "B09-spikes-difficulty_point-color=orange",
  "B10-laser_show-difficulty_point-color=orange",
  "B11-lasers-difficulty_point-color=orange",
  "B12-blocks-difficulty_point-color=orange",
  "B13-conveyor_belts-difficulty_point-color=orange",
  "B14-laser_show-difficulty_point-color=orange",
  "B15-action-difficulty_point-color=orange",
  "B16-action-exploration-point-difficulty_point-color=orange",
  "B17-action-difficulty_point-color=orange",
  "B18-mr_dance_boss-exploration_point-difficulty_point-color=orange",
  "B19-reward",
];
var chapterC = [
  "C01",
  "C01.1",
  "C02",
  "C03",
  "C04",
  "C05",
  "C06",
  "C07",
  "C08",
  "C09",
  "C10",
  "C11",
  "C12",
  "C13",
  "C13.1",
  "C14",
  "C15",
  "C16",
  "C17",
  "C18",
  "C19",
  "C20",
  "C21",
  "C22",
];
var chapterD = [
  "D01",
  "D02",
  "D03",
  "D03.1",
  "D04",
  "D05",
  "D05.1",
  "D05.2",
  "D06",
  "D06.1",
  "D06.2",
  "D06.3",
  "D06.4",
  "D06.5",
  "D07",
  "D08",
  "D09",
  "D10",
  "D10.1",
  "D11",
  "D12",
  "D13",
  "D14",
  "D15",
  "D16",
  "D17",
  "D18",
  "D19",
  "D20",
];
var chapterE = [
  "E01",
  "E02",
  "E03",
  "E03.1",
  "E04",
  "E05",
  "E06",
  "E07",
  "E08",
  "E09",
  "E10",
  "E11",
  "E12",
  "E13",
  "E14",
  "E15",
  "E15.1",
  "E15.2",
  "E16",
  "E17",
  "E18",
  "E19",
  "E19.1",
];
